name: Caddy Plugin CI

on:
  push:
    paths:
      - 'caddy-plugin/**'
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caddy-plugin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Plugin
        run: go build ./...

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Test (Optional)
        run: go test -v ./... || echo "No tests found (safe to ignore if empty plugin)"
